---
author: ~
build_requires:
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: 'Module::Install version 0.80'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jifty-Plugin-YouTube
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Jifty: 0.90409
version: 0.01
